use_frameworks!

target 'SideMenuController_Example' do
  pod 'SideMenuController', :path => '../'

  target 'SideMenuController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase', '~> 2.1'
    pod 'Quick', '~> 0.9'
    pod 'Nimble', '~> 4.1'
    pod 'Nimble-Snapshots', '~> 4.1'
  end
end
